import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-e11-inspeccion-tanques-registros',
  templateUrl: './e11-inspeccion-tanques-registros.page.html',
  styleUrls: ['./e11-inspeccion-tanques-registros.page.scss'],
})
export class E11InspeccionTanquesRegistrosPage implements OnInit {

  programaMantenimiento:any=[
    {
      areaEquipo:'Tanques',
      planMantenimiento:[
        'Limpieza área de almacenamiento',
        'Inspección bomba, control inventarios',
        'Prueba sensores, bomba, espacio anular',
        'Inspección, estado contenedores, botas, boquillas y tapas',
        'Prueba de hermeticidad, control de inventarios',
        'Medición y purga de agua, si aplica',
        'Revisión válvula sobrellenado, en operación y completa',
        'Pruebas de hermeticidad equipo móvil.'
      ],
      periodo:[
        'Diaria',
        'Mensual',
        'Mensual',
        'Mensual',
        'Mensual',
        'Mensual',
        '6 Meses',
        'Anual',
      ],
      meses:[
        {
          Ene:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Feb:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Mar:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            ''
          ]
        },
        {
          Abr:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          May:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Jun:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Jul:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Ago:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Sep:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Oct:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Nov:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Dic:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        }
      ],
      reporte:[
        'F-06',
        'F-01',
        'F-02',
        'F-01',
        'B',
        'B',
        'B'
      ]
    },
    {
      areaEquipo:'Dispensarios / Tuberias',
      planMantenimiento:[
        'Limpieza gabinete, manguera, pistola',
        'Inspección contenedores y accesorios, sin fuga, buen estado',
        'Prueba de válvula shut-off',
        'Prueba sensor de líquidos',
        'Calibración',
        'Inspección de protectores y anclajes',
        'Inspección de fugas en accesorios, válvulas',
        'Tubería de venteo, integridad Mecánica',
        'Revisión de válvulas de venteo',
        'Revisión de arrestador de flama',
        'Pruebas de hermeticidad'
      ],
      periodo:[
        'Diaria',
        'Mensual',
        'Mensual',
        'Mensual',
        'Anual',
        'Mensual',
        'Mensual',
        'Mensual',
        '6 Meses',
        '6 Meses',
        'Anual',
      ],
      meses:[
        {
          Ene:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            '',
            '',
            ''
          ]
        },
        {
          Feb:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            '',
            'X',
            ''
          ]
        },
        {
          Mar:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Abr:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            '',
            '',
            ''
          ]
        },
        {
          May:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            '',
            '',
            ''
          ]
        },
        {
          Jun:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            '',
            '',
            ''
          ]
        },
        {
          Jul:[
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            ''
          ]
        },
        {
          Ago:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            'X',
            'X',
            ''
          ]
        },
        {
          Sep:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            '',
            '',
            'X'
          ]
        },
        {
          Oct:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            '',
            '',
            ''
          ]
        },
        {
          Nov:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            '',
            '',
            ''
          ]
        },
        {
          Dic:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            'X',
            '',
            '',
            ''
          ]
        }
      ],
      reporte:[
        'F-03',
        'F-03',
        'F-02',
        'F-02',
        'R',
        '',
        'F-04',
        'F-04',
        'F-04',
        'F-04',
        'R',
        'F-07',
        'R'
      ]
    },
    {
      areaEquipo:'Extintores',
      planMantenimiento:[
        'Inspección, ubicación y estado de accesorios.',
        'Recarga de polvo o gas.'
      ],
      periodo:[
        'Mensual',
        'Anual'
      ],
      meses:[
        {
          Ene:[
            'X',
            ''
          ]
        },
        {
          Feb:[
            'X',
            ''
          ]
        },
        {
          Mar:[
            'X',
            ''
          ]
        },
        {
          Abr:[
            'X',
            ''
          ]
        },
        {
          May:[
            'X',
            ''
          ]
        },
        {
          Jun:[
            'X',
            ''
          ]
        },
        {
          Jul:[
            'X',
            'X'
          ]
        },
        {
          Ago:[
            'x',
            ''
          ]
        },
        {
          Sep:[
            'x',
            ''
          ]
        },
        {
          Oct:[
            'x',
            ''
          ]
        },
        {
          Nov:[
            'x',
            ''
          ]
        },
        {
          Dic:[
            'x',
            ''
          ]
        }
      ],
      reporte:[
        'F-07',
        'R'
      ]
    },
    {
      areaEquipo:'Drenajes Registros, Trampa de combustibles',
      planMantenimiento:[
        'Inspección de trampa que esté libre de hidrocarburos',
        'Limpieza Rejillas, registros y trampa.',
        'Limpieza ecológica, desazolve de registros y trampa',
        'Retiro Residuos peligrosos'
      ],
      periodo:[
        'Diaria',
        'Mensual',
        '3 Meses',
        '3 Meses'
      ],
      meses:[
        {
          Ene:[
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Feb:[
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Mar:[
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Abr:[
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          May:[
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Jun:[
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Jul:[
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Ago:[
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Sep:[
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Oct:[
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Nov:[
            'X',
            'X',
            '',
            ''
          ]
        },
        {
          Dic:[
            'X',
            'X',
            '',
            ''
          ]
        }
      ],
      reporte:[
        'F-06',
        'B',
        'R',
        'R'
      ]
    },
    {
      areaEquipo:'Áreas Verdes',
      planMantenimiento:[
        'Poda y limpieza'
      ],
      periodo:[
        '15 días'
      ],
      meses:[
        {
          Ene:[
            'X'
          ]
        },
        {
          Feb:[
            ''
          ]
        },
        {
          Mar:[
            ''
          ]
        },
        {
          Abr:[
            'X'
          ]
        },
        {
          May:[
            ''
          ]
        },
        {
          Jun:[
            ''
          ]
        },
        {
          Jul:[
            'X'
          ]
        },
        {
          Ago:[
            ''
          ]
        },
        {
          Sep:[
            ''
          ]
        },
        {
          Oct:[
            'X'
          ]
        },
        {
          Nov:[
            ''
          ]
        },
        {
          Dic:[
            ''
          ]
        }
      ],
      reporte:[
        ''
      ]
    },
    {
      areaEquipo:'Instalaciones eléctricas',
      planMantenimiento:[
        'Instalaciones eléctricas',
        'Inspección de alumbrado',
        'Revisión y prueba de Paros de emergencia',
        'Inspección general de Instalaciones (integridad eléctrica)',
        'Medición de resistividad tierras y limpieza',
        'Mantenimiento a Respaldo (UPS)',
        'Dictamen por una UVIE'
      ],
      periodo:[
        'Mensual',
        'Mensual',
        'Mensual',
        '6 Meses',
        'Anual',
        'Anual',
        '5 Años'
      ],
      meses:[
        {
          Ene:[
            'X',
            'X',
            'X',
            '',
            '',
            '',
            ''
          ]
        },
        {
          Feb:[
            'X',
            'X',
            'X',
            '',
            '',
            'X',
            ''
          ]
        },
        {
          Mar:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            ''
          ]
        },
        {
          Abr:[
            'X',
            'X',
            'X',
            '',
            '',
            '',
            ''
          ]
        },
        {
          May:[
            'X',
            'X',
            'X',
            '',
            '',
            '',
            ''
          ]
        },
        {
          Jun:[
            'X',
            'X',
            'X',
            '',
            '',
            '',
            ''
          ]
        },
        {
          Jul:[
            'X',
            'X',
            'X',
            '',
            '',
            '',
            ''
          ]
        },
        {
          Ago:[
            'X',
            'X',
            'X',
            '',
            '',
            '',
            ''
          ]
        },
        {
          Sep:[
            'X',
            'X',
            'X',
            'X',
            '',
            '',
            ''
          ]
        },
        {
          Oct:[
            'X',
            'X',
            'X',
            '',
            '',
            '',
            'X'
          ]
        },
        {
          Nov:[
            'X',
            'X',
            'X',
            '',
            'X',
            '',
            ''
          ]
        },
        {
          Dic:[
            'X',
            'X',
            'X',
            '',
            '',
            '',
            ''
          ]
        }
      ],
      reporte:[
        'F-02',
        'B',
        'F-02',
        'F-05',
        'R',
        'R',
        'D'
      ]
    },
    {
      areaEquipo:'Señalamientos',
      planMantenimiento:[
        'Inspección señalamientos basura, no estacionarse, etc.',
        'Inspección señalamientos horizontales',
        'Rotulación/sustitución de señalamientos horizontales',
        'Pintura y rotulación tapas contenedores tanques',
        'Pintura y rotulación tapas pozos de monitoreo observación.',
        'Pintura de tapas de registros eléctricos y drenajes.'
      ],
      periodo:[
        '4 Meses',
        '4 Meses',
        '6 Meses',
        'Anual',
        'Anual',
        'Anual'
      ],
      meses:[
        {
          Ene:[
            'x',
            'x',
            'x'
          ]
        },
        {
          Feb:[
            'x',
            'x',
            'x'
          ]
        },
        {
          Mar:[
            'x',
            'x',
            'x'
          ]
        },
        {
          Abr:[
            'x',
            'x',
            'x'
          ]
        },
        {
          May:[
            'x',
            'x',
            'x'
          ]
        },
        {
          Jun:[
            'x',
            'x',
            'x'
          ]
        },
        {
          Jul:[
            'x',
            'x',
            'x'
          ]
        },
        {
          Ago:[
            'x',
            'x',
            'x'
          ]
        },
        {
          Sep:[
            'x',
            'x',
            'x'
          ]
        },
        {
          Oct:[
            'x',
            'x',
            'x'
          ]
        },
        {
          Nov:[
            'x',
            'x',
            'x'
          ]
        },
        {
          Dic:[
            'x',
            'x',
            'x'
          ]
        }
      ],
      reporte:[
        'B',
        'B',
        'F-02'
      ]
    },
    {
      areaEquipo:'Otros Equipos',
      planMantenimiento:[
        'Revisión de compresor, lubricación',
        'Revisión de hidroneumático.',
        'Revisión de bombas de agua',
        'Revisión de CCTV',
        'Revisión de accesorios de descarga, codos, mangueras'
      ],
      periodo:[
        'Mensual',
        'Mensual',
        'Mensual',
        'Mensual',
        'Mensual'
      ],
      meses:[
        {
          Ene:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Feb:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Mar:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Abr:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          May:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Jun:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Jul:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Ago:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Sep:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Oct:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Nov:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        },
        {
          Dic:[
            'X',
            'X',
            'X',
            'X',
            'X'
          ]
        }
      ],
      reporte:[
        'B',
        'B',
        'B',
        'B',
        'F-04'
      ]
    },
    {
      areaEquipo:'Edificios',
      planMantenimiento:[
        'Limpieza',
        'Orden, cuarto eléctrico, sucios, Máquinas, Alm. Res. Peligroso',
        'Azoteas, Revisión de bajadas de agua',
        'Revisión de pavimentos, libre de baches, fisuras.',
        'Revisión de pisos de almacenamiento despacho sin fisuras.',
        'Revisión de tinacos y cisternas'
      ],
      periodo:[
        'Diaria',
        'Diaria',
        'Mensual',
        '4 Meses',
        '4 Meses',
        '6 Meses'
      ],
      meses:[
        {
          Ene:[
            'X',
            'X',
            'X',
            '',
            'X',
            ''
          ]
        },
        {
          Feb:[
            'X',
            'X',
            'X',
            '',
            'X',
            ''
          ]
        },
        {
          Mar:[
            'X',
            'X',
            'X',
            'X',
            'X',
            ''
          ]
        },
        {
          Abr:[
            'X',
            'X',
            'X',
            '',
            'X',
            ''
          ]
        },
        {
          May:[
            'X',
            'X',
            'X',
            '',
            'X',
            ''
          ]
        },
        {
          Jun:[
            'X',
            'X',
            'X',
            '',
            'X',
            ''
          ]
        },
        {
          Jul:[
            'X',
            'X',
            'X',
            'x',
            'X',
            ''
          ]
        },
        {
          Ago:[
            'X',
            'X',
            'X',
            '',
            'X',
            ''
          ]
        },
        {
          Sep:[
            'X',
            'X',
            'X',
            '',
            'X',
            ''
          ]
        },
        {
          Oct:[
            'X',
            'X',
            'X',
            '',
            'X',
            ''
          ]
        },
        {
          Nov:[
            'X',
            'X',
            'X',
            'X',
            'X',
            ''
          ]
        },
        {
          Dic:[
            'X',
            'X',
            'X',
            '',
            'X',
            ''
          ]
        }
      ],
      reporte:[
        'F-06',
        'F-06',
        'b',
        'b',
        'b',
        'b'
      ]
    }
  ]

  

  lists:[
    {
    "nodename": "Main application Server",
    "enabled": true
    },
    {
    "nodename": "Main Server",
    "enabled": false
    }
  ]

  constructor() { }

  ngOnInit() {
  }

}
